// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nikhil133/duplo/src/serviceinterface (interfaces: WeatherServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	service "github.com/nikhil133/duplo/src/service"
	request "github.com/nikhil133/duplo/utils/request"
	reflect "reflect"
)

// MockWeatherServiceInterface is a mock of WeatherServiceInterface interface
type MockWeatherServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherServiceInterfaceMockRecorder
}

// MockWeatherServiceInterfaceMockRecorder is the mock recorder for MockWeatherServiceInterface
type MockWeatherServiceInterfaceMockRecorder struct {
	mock *MockWeatherServiceInterface
}

// NewMockWeatherServiceInterface creates a new mock instance
func NewMockWeatherServiceInterface(ctrl *gomock.Controller) *MockWeatherServiceInterface {
	mock := &MockWeatherServiceInterface{ctrl: ctrl}
	mock.recorder = &MockWeatherServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWeatherServiceInterface) EXPECT() *MockWeatherServiceInterfaceMockRecorder {
	return m.recorder
}

// DeleteCoordinates mocks base method
func (m *MockWeatherServiceInterface) DeleteCoordinates(arg0 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCoordinates", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCoordinates indicates an expected call of DeleteCoordinates
func (mr *MockWeatherServiceInterfaceMockRecorder) DeleteCoordinates(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCoordinates", reflect.TypeOf((*MockWeatherServiceInterface)(nil).DeleteCoordinates), arg0)
}

// GetCoordinates mocks base method
func (m *MockWeatherServiceInterface) GetCoordinates() ([]service.Coordinate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoordinates")
	ret0, _ := ret[0].([]service.Coordinate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoordinates indicates an expected call of GetCoordinates
func (mr *MockWeatherServiceInterfaceMockRecorder) GetCoordinates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoordinates", reflect.TypeOf((*MockWeatherServiceInterface)(nil).GetCoordinates))
}

// GetForcast mocks base method
func (m *MockWeatherServiceInterface) GetForcast(arg0 request.Request) (*service.Forecast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForcast", arg0)
	ret0, _ := ret[0].(*service.Forecast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForcast indicates an expected call of GetForcast
func (mr *MockWeatherServiceInterfaceMockRecorder) GetForcast(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForcast", reflect.TypeOf((*MockWeatherServiceInterface)(nil).GetForcast), arg0)
}
